### ISSUE TITLE
A PHP Error was encountered

### ISSUE THREAD

**Issue by Uzenmi** [gocart/GoCart3#17]
I have just upload GoCart3 to Ipage Hosting, its an error:

_"Parse error: syntax error, unexpected '[' in /gocart/application/controllers/Bootstrap.php on line 20"_

And I can't install it.

**Comment by gocart** [comment]
PHP 5.4 or greater is required, GoCart 3 uses the new array syntax throughout the code.

**Comment by Uzenmi** [comment]
Okay, thanks.
