### ISSUE TITLE
Product category bugs

### ISSUE THREAD

**Issue by Uzenmi** [gocart/GoCart3#20]
Have some bugs:
1. Size_limit of image file upload. Its not config.
2. Image file of category is not deleted from server when I deleted that category.
3. Main image checkbox for product does not show checked (product update form).
4. Slug of category, if I add a character to category slug (ex: "2"), its error as below: [https://demo.gocartdv.com/woGf372/category/laptops2](https://demo.gocartdv.com/woGf372/category/laptops2)

**Comment by gocart** [comment]
1 & 2. https://github.com/gocart/GoCart3/commit/37a579a9706df1951e147f17c581d3606331be0c
3. https://github.com/gocart/GoCart3/commit/6d249444a9a8fa50e3b83496376f2eec37092bb2
4. https://github.com/gocart/GoCart3/commit/f35a73e27f92a7066915bc3b56b9c4ca28a7ab63
