### ISSUE TITLE
User address can not loaded

### ISSUE THREAD

**Issue by Uzenmi** [gocart/GoCart3#21]
The User address #addresses can not loaded in user account information page.

(P/s: It is seems that you are a little bit slow to fix bugs).

**Comment by gocart** [comment]
Uzenmi, I would remind you that GoCart is built by a small team. The majority of our time is spent helping paying customers.

https://github.com/gocart/GoCart3/commit/82b5d7eea5ee8ea8756bb5d91b79c6f7dc2540d0
