### ISSUE TITLE
Add an empty row to order table

### ISSUE THREAD

**Issue by Uzenmi** [gocart/GoCart3#22]
I am a newbie on the programmer, and I do not know why we need to add an empty row with 'status'=>'cart' to the order table? Thanks.

**Comment by gocart** [comment]
When someone is on the shop, they are automatically registered as a guest and assigned an order in the db. This way we can add additional features in the future that allow us to track orders with a greater level of detail.

**Comment by Uzenmi** [comment]
Thanks.
