### ISSUE TITLE
Bulk save buttons are displayed over the table headers in product's admin page in Firefox

### ISSUE THREAD

**Issue by buzkall** [gocart/GoCart3#23]
In chrome it's ok, but in Firefox you need to clear the float or surround the whole form#bulk_form with a div (a class=row, for example)

<img width="1788" alt="screen shot 2015-08-25 at 21 09 43" src="https://cloud.githubusercontent.com/assets/5702/9476566/9fd6f3e6-4b6d-11e5-9c79-bc1dd893bd94.png">

**Comment by gocart** [comment]
https://github.com/gocart/GoCart3/commit/58480993a521efe7b1f1aa4c8abbe932dc1ecfb9
