### ISSUE TITLE
Omnipay

### ISSUE THREAD

**Issue by olimortimer** [gocart/GoCart3#25]
I noticed Omnipay is in the composer.json, and wondered if you have any docs on how this is implemented within GoCart?  I'm interested in using Paypal Express, as that's what I use in GoCart 2.

Thanks!

**Comment by gocart** [comment]
The core library is included in the composer.json but not used unless a module is built to support a particular payment method. We're still working on some of the payment methods that were available for GoCart 2. We do have a Paypal Pro module built using omnipay available on our site already.

https://gocartdv.com/product/paypal-pro-3x

The modules themselves will contain the companion libraries for whichever payment method they support if OmniPay is the right way to go for it.

**Comment by olimortimer** [comment]
Thanks Noah.  I would be looking at Paypal Express at the moment, as PayPal Pro requires a monthly subscription for little benefit (IMO).

The Omnipay PayPal driver supports Express, Pro and Rest, so guessing your module could be easily changed to support the others?  https://github.com/thephpleague/omnipay-paypal

I'm also looking at Stripe at the moment, as that looks very competitive vs PayPal - which also has an Omnipay driver https://github.com/thephpleague/omnipay-stripe

**Comment by gocart** [comment]
The stripe driver for omnipay does not utilize stripe.js which helps offset the PCI demands by not posting directly to the server. For now I would recommend going with the Stripe module we have in our shop.

**Comment by zhangxiansong** [comment]
能不能写中文呢

**Comment by olimortimer** [comment]
@zhangxiansong "You can not write Chinese" ?

**Comment by olimortimer** [comment]
It looks like Omnipay: Stripe supports Stripe.js now - do you have any plans to implement this into your Stripe payment method?

https://github.com/thephpleague/omnipay-stripe

**Comment by gocart** [comment]
We have a stripe method already supported. It's unlikely we would update it to utilize omnipay at this time.
