### ISSUE TITLE
Input form renders too big in Firefox

### ISSUE THREAD

**Issue by buzkall** [gocart/GoCart3#26]
It seems Firefox doesn't handle ok the fixed height in the input form

Firefox:
![screen shot 2015-08-27 at 08 38 07](https://cloud.githubusercontent.com/assets/5702/9514238/a625cf20-4c98-11e5-8ca3-b7e2937caefe.png)

Chrome:
![screen shot 2015-08-27 at 08 38 18](https://cloud.githubusercontent.com/assets/5702/9514239/a62f432a-4c98-11e5-91f3-a5603b30ec72.png)

It seems it can be fixed adding a height: auto to the admin.css file
Something like this:

.input-append .form-control {height: auto}

**Comment by gocart** [comment]
If you would like to submit a pull-request for this then we would be happy to pull it in.
