### ISSUE TITLE
Add redactor to the Product Option Value field

### ISSUE THREAD

**Issue by Uzenmi** [gocart/GoCart3#27]
Can you please show me how to add redactor to the "name" field of Product Option Values, I try to do that on product_form.php page but may be javascript didn't run. Thanks.

**Comment by gocart** [comment]
The Name field on the product options values is a text field and as such does not support a wysiwyg editor. You would have to change it to a text area and dynamically add the redactor instance to it. You would also have to update the front end to give appropriate space to the content.
