### ISSUE TITLE
Admin: Product Options

### ISSUE THREAD

**Issue by olimortimer** [gocart/GoCart3#3]
Product options don't show in the admin section when editing a product.  This means that when you save the product, any options that have been previously set (and so not showing), are deleted.

**Comment by gocart** [comment]
What browser and version are you using to get these results?

**Comment by olimortimer** [comment]
The latest Google Chrome, version 44.0.2403.107 (64-bit) on Mac OS X Yosemite.

I can add options to a product, but when I edit the same product, the options have vanished.  They are still in the database and on the product page in front end, however if I then save the product in the admin, the options are deleted from the database.

**Comment by gocart** [comment]
Fixed with f57aea4acca2b2001cb4bf83518bb42f8effc037

**Comment by olimortimer** [comment]
Excellent, thanks
