### ISSUE TITLE
CSRF protection

### ISSUE THREAD

**Issue by arashsaffari** [gocart/GoCart3#31]
if CSRF protection is set to true, works GoCart3 wrong.

**Comment by gocart** [comment]
GoCart does not support the CSFR function of CodeIgniter.

**Comment by arashsaffari** [comment]
Could you tell me why?
this is an important security function.

**Comment by gocart** [comment]
There are a couple reasons.
1. GoCart was started before this feature was implemented in CodeIgniter. The amount of coded needed to implement is properly would be substantial.
2. GoCart is built on CodeIgniter, but it's a modified version and as such not every CodeIgniter library has been thoroughly tested. (We use an alternate view system and session library for instance). You might also notice that our controllers use namespaces, we have modular architecture, and there is a static facade for the CI super object.

You're welcome to fork GoCart and add in the features you're looking for. If you feel your contribution is important you can submit a pull request with your changes.
