### ISSUE TITLE
Shopping cart order insert

### ISSUE THREAD

**Issue by thijmenvenus** [gocart/GoCart3#34]
I recently downloaded and installed gocart 3. After the installation I got error in the frontend saying that gocart wants to insert an order but billing_address_id doesn't have a default value. I found out that gocart attemted to insert an order with only a 'status' and a 'customer_id', but the orders table has many more mandatory(not null) fields. Is this a known bug? and how do I go about fixing this?

**Comment by gocart** [comment]
I've not had this experience. You may need to check your MySQL settings to ensure you're not operating in strict mode.

**Comment by smileservices** [comment]
Hello! I am playing with an installation of GoCart3 and I've seen this behaviour also. It appears that in the core GoCart.php, at the getCart function, if the order for the specific visitor doesn't exist in the db (which for a guest it doesn't, of course) then a new blank order is saved into the db while a new guest user is also saved. Why aren't you managing the cart content for the guests in the session? I wouldn't want two blank rows in my db for every visitor, it's bad practice.
