### ISSUE TITLE
Fields appended with _1

### ISSUE THREAD

**Issue by olimortimer** [gocart/GoCart3#36]
I'm sure I saw a commit a while back, which removed fields with _1 etc, but I can't find it.  However I've noticed some still exist, and wondered if these can be removed?  For example:

``` categories.enabled_1
order_items.enabled_1
order_items.price_1
order_items.saleprice_1
products.enabled_1
products.price_1
products.saleprice_1
```

**Comment by gocart** [comment]
Nope, Those are important parts of GoCart 3.

Basically, GoCart 3 utilizes customer groups in a different manner from GoCart 2.

GoCart 2 offered across the board discounts on products, while GoCart 3 actually offers custom pricing / availability for different user groups.

The _number references the price, sale price and availability for a particular user group with the number relating to that groups ID.

**Comment by olimortimer** [comment]
So adding more groups would require extra fields in a table?  Ie enabled_2, price_2 etc?  Does GoCart 3 automatically add and remove these from a table when a group is created / deleted?

Would a link table not be better?  Ie

product_id, group_id, type, value
1, 1, 'enabled', 1
2, 1, 'enabled, 0
1, 1, 'price', 5.99
1, 1, 'saleprice', 3.99

**Comment by gocart** [comment]
ok so I'll answer in order.
1. Yes GoCart 3 creates the columns as needed.
2. No, they are not removed when groups are removed. They could be, but there could also be history there that someone might want to keep intact so for that reason I left them in place, though it would be trivial to remove them if desired.
3. A link table wouldn't really help much since it would just be creating one to one relationships and would complicate some of the existing queries with otherwise unnecessary joins.

**Comment by olimortimer** [comment]
Hmm ok.  IMO adding fields on the fly for things like this is a bit...messy.

**Comment by gocart** [comment]
There would be many queries to be rewritten, with additional joins / modified sorting etc. to adjust as well as forms. Multiple tables get adjusted. We also have some unreleased code right now that does table rate pricing on products etc.

Changing it would be time consuming and would yield little benefit but if it's something you feel strongly about you could always make the appropriate adjustments and send us a pull request to review, though I cannot guarantee that it would be accepted.

**Comment by olimortimer** [comment]
From a performance perspective, if you had thousands of products, adding a new customer group would potentially lock the whole database whilst it creates the 3 new columns in the product table, and the associated default values, for every single product.

IMO a join, or even a subquery, would be much more efficient than creating additional fields.  In regards to not removing the fields when a group is removed, if they were stored in a separate table, you could just set them to inactive if you wanted to keep them for historical purposes.  However, deleting anything should really remove all traces of it.  If you want to keep the info for later use, then an active / inactive flag is a far better solution.

**Comment by gocart** [comment]
We'll work this change in our next version of GoCart.

**Comment by Uzenmi** [comment]
I am waiting for  :)

I think it really need some fields for next version:

**1. In Product:**
- Date range for sales price (from date - to date).
- Video
- Google Map
- Related product: Added for categories
- Images: Can be select images from Media (likes Wordpress or Opencart) & added multi images.

**2. In Digital Product:**
- The Price, Sales Price, Date range, option yes/no added to product price (some customers want download file only), coupon code applied for this.
- Description.
- Associate Products with the downloadable files (its like Digital Product tab in the Product Form).

**3. In Administrator:**
- Access: Add the Shop Manager Access with admin's permission.

**4. Partner:**
- Add the Partner module: they can be add product, digital product... option yes/no admin's approval 
  .

**5. In Configuration:**
- Google Map: Add the Google Map for shop local.

**6. Themes Switcher:**
- Add mobile, tablet, pc theme detector

Thanks.
