### ISSUE TITLE
Cart: Product Options

### ISSUE THREAD

**Issue by olimortimer** [gocart/GoCart3#4]
During checkout the product is stored in order_item_options, with options.name in order_item_options.option_name, but the chosen options_value in order_item_options.value, is the options_value.id, rather than options_value.name.  This means the cart summary also shows the options_value.id against the name of the option.

**Comment by gocart** [comment]
Hey Oli, thanks for letting me know about these bugs!

Fixed with e04a5c6d16b81d7512ad86d47f4d7f13d37c453c

**Comment by olimortimer** [comment]
No problem Noah - unfortunately I didn't have time to dig into the issue, fix and submit a pull request, so thought I would create an issue any way. If I get chance, I'll always fix the issue.

Should the options value in the admin be a required field?  Reason being is that you can add an option with a blank value, which means the value won't show in the checkout / order.
