### ISSUE TITLE
Add to cart not working in Mobile Web browser

### ISSUE THREAD

**Issue by PRDinesh** [gocart/GoCart3#40]
I have setup the gocart in the following url http://www.bubbleoutlooks.com.  Now when I do add to cart from mobile browser, the item is not added to cart.  Can you help me to debug the issue.

**Comment by skynetweb** [comment]
Hi there, 
I have tested your website on the mobile browser and it works adding items to the cart. 
What are you using to replicate this issue ?

**Comment by gocart** [comment]
Closing due to no response.
