### ISSUE TITLE
Status of GoCart3

### ISSUE THREAD

**Issue by olimortimer** [gocart/GoCart3#44]
I'm looking into purchasing 'Stripe for GoCart 3.x' and 'White Label License 3.x' but I want to ensure that GoCart3 is still active, and being developed - the GitHub repo seems to be stagnant at the moment, as the last commit was 6 months ago, and issues aren't being answered.

Can we expect continued development from the GoCart team?

**Comment by gocart** [comment]
Clear Sky Designs has shut down and GoCart has transferred to new owners. GoCart will continue to be maintained.
