### ISSUE TITLE
How to make menu like this

### ISSUE THREAD

**Issue by Uzenmi** [gocart/GoCart3#49]
Hi,

Can you please show me how to make a menu as below with Categories and Products?
![menu](https://cloud.githubusercontent.com/assets/9086654/21093359/ec3883f8-c083-11e6-9acb-a132dd0f4e1c.jpg)

Thank you so much.

**Comment by gocart** [comment]
Unfortunately we cannot provide support for this sort of customization. I would recommend that you hire a qualified developer or contact Jericho Studios for a quote @ https://jerichostudios.com/#four

**Comment by Uzenmi** [comment]
Thanks.
