### ISSUE TITLE
Watermark for images

### ISSUE THREAD

**Issue by Uzenmi** [gocart/GoCart3#50]
Hi, I want to make watermark text for images, in products/controllers/AdminProducts.php file,  before line `\CI::image_lib()->initialize($config);` I added:
```
$config['wm_text'] = 'ABC';
$config['wm_type'] = 'text';
$config['wm_font_path'] = 'system/fonts/texb.ttf';
$config['wm_font_size'] = '30';
$config['wm_font_color'] = 'ffff00';
$config['wm_vrt_alignment'] = 'bottom';
$config['wm_hor_alignment'] = 'right';
$config['wm_padding'] = '0';
```
And before line` \CI::image_lib()->resize();`, I added:

```\CI::image_lib()->watermark();```

But it did not success. Can you please help me? Thanks.

**Comment by olimortimer** [comment]
The problem you have, is that you are running watermark onto your src image into your dest location, but then immediately running resize afterwards, which is overwriting your watermarked image with a resized version.

What you would need to do is to watermark the `uploads/images/full/` version, then the resize for medium, small and thumbnail will use the watermarked version.

So under the following:

`\CI::load()->library('image_lib');`

Add:

```
// Watermark our image
$config['image_library'] = 'gd2';
$config['source_image'] = 'uploads/images/full/'.$upload_data['file_name'];
$config['new_image'] = 'uploads/images/full/'.$upload_data['file_name'];
$config['wm_text'] = 'ABC';
$config['wm_type'] = 'text';
$config['wm_font_path'] = 'system/fonts/texb.ttf';
$config['wm_font_size'] = '30';
$config['wm_font_color'] = 'ffff00';
$config['wm_vrt_alignment'] = 'bottom';
$config['wm_hor_alignment'] = 'right';
$config['wm_padding'] = '0';
\CI::image_lib()->initialize($config);
\CI::image_lib()->watermark();
\CI::image_lib()->clear();
```

This will take the full source image, add the watermark, and save it over the top of itself.
